language: node_js
node_js: node
cache: yarn
branches:
  only:
    - master
install:
  - yarn
jobs:
  include:
    - stage: Build
      script: yarn build
    - stage: Test
      script: yarn test --coverage && yarn add codecov -g && codecov
    - stage: Deploy Website
      script: yarn build-storybook && yarn add netlify-cli -g && netlify deploy --prod --site $NETLIFY_SITE_ID --auth=$NETLIFY_ACCESS_TOKEN --dir=storybook-static
